import type { Metadata } from "next";
import "./globals.css";

const SITE_URL = "https://danang-dev.my.id";

export const metadata: Metadata = {
  title: "Danang — Cloud DevOps Engineer",
  description:
    "Cloud DevOps Engineer focused on cloud infrastructure, automation, and reliable software delivery.",
  metadataBase: new URL(SITE_URL),
  alternates: { canonical: "/" },
  keywords: [
    "Cloud DevOps Engineer",
    "AWS",
    "GCP",
    "Alibaba Cloud",
    "Kubernetes",
    "Terraform",
    "CI/CD",
    "Infrastructure",
  ],
  authors: [{ name: "Danang" }],
  openGraph: {
    title: "Danang — Cloud DevOps Engineer",
    description:
      "Cloud DevOps Engineer focused on cloud infrastructure, automation, and reliable software delivery.",
    type: "website",
    url: "/",
    // og:image is generated by app/opengraph-image.tsx (file convention)
  },
  twitter: {
    card: "summary_large_image",
    title: "Danang — Cloud DevOps Engineer",
    description:
      "Cloud DevOps Engineer focused on cloud infrastructure, automation, and reliable software delivery.",
    // twitter:image falls back to the Open Graph image
  },
  icons: {
    icon: "/assets/logo.svg",
    apple: "/assets/logo.svg",
  },
  robots: { index: true, follow: true },
};

/*
  Schema.org Person structured data. Every field is sourced from content
  already present in this codebase — the page metadata and the footer's
  contact and social links. Nothing is invented.
*/
const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Danang",
  jobTitle: "Cloud DevOps Engineer",
  url: SITE_URL,
  email: "mailto:danangadi2005@gmail.com",
  sameAs: [
    "https://linkedin.com/in/danangadi",
    "https://github.com/dananggadii",
  ],
  knowsAbout: [
    "Cloud DevOps Engineer",
    "AWS",
    "GCP",
    "Alibaba Cloud",
    "Kubernetes",
    "Terraform",
    "CI/CD",
    "Infrastructure",
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap"
          rel="stylesheet"
        />
        {/* Person structured data — invisible to users, read by crawlers */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />
      </head>
      <body
        className="font-sans antialiased overflow-x-hidden"
        style={{ backgroundColor: "#FAFAF8", color: "#1A1A1A" }}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
